name: Run Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs nightly at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: ls
      run: ls -R
