name: Run Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs nightly at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcoap3-dev libldns-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/anr-bmbf-pivot/aiodnsprox/

    - name: Running test
      run: ./testing/test.sh

    - name: Print debugging files
      run: |
        for file in testing/*.txt; do
          echo "File: $file"
          cat "$file"
        done
