name: Run Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs nightly at midnight UTC

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: testing
      run: ../testing/test.sh
